<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <meta name="author" content=" ">
    <meta name="description" content="/">
    <meta name="keywords" content="blog, economics,personal">
    
    <meta property="og:site_name" content="Smooth as consumption">
    <meta property="og:title" content="
  Estratègia òptima en exàmens de recuperació - Smooth as consumption
">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
    <meta property="og:url" content="/posts/examen_recu/">
    <meta property="og:image" content="/">
    <meta name="twitter:card" content="summary">
    <meta name="twitter:site" content="/posts/examen_recu/">
    <meta name="twitter:image" content="/">

    <base href="../../">
    <title>
  Estratègia òptima en exàmens de recuperació - Smooth as consumption
</title>

    <link rel="canonical" href="../../posts/examen_recu/">
    
    <link  rel="stylesheet" href="https://fonts.googleapis.com/css?family=Fira+Mono:400,700">
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">
    <link rel="stylesheet" href="../../css/style.min.css">

    

    

    <link rel="icon" type="image/png" href="../../images/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="../../images/favicon-16x16.png" sizes="16x16">

    

    <meta name="generator" content="Hugo 0.55.6" />
  </head>

  <body class="">
    <main class="wrapper">
      <nav class="navigation">
  <section class="container">
    <a class="navigation-title" href="../../">Smooth as consumption</a>
    <input type="checkbox" id="menu-control"/>
    <label class="menu-mobile  float-right " for="menu-control">
      <span class="btn-mobile  float-right ">&#9776;</span>
      <ul class="navigation-list">
        
          
            <li class="navigation-item  align-center ">
              <a class="navigation-link" href="../../about">About</a>
            </li>
          
            <li class="navigation-item  align-center ">
              <a class="navigation-link" href="../../projects">Projects</a>
            </li>
          
            <li class="navigation-item  align-center ">
              <a class="navigation-link" href="../../posts">Blog</a>
            </li>
          
            <li class="navigation-item  align-center ">
              <a class="navigation-link" href="../../pages/site">Site</a>
            </li>
          
        
        
      </ul>
    </label>
  </section>
  

    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>
    
</nav>


      <div class="content">
        
  <section class="container post">
  <article>
    <header>
      <h1 class="title">Estratègia òptima en exàmens de recuperació</h1>
      <h2 class="date">July 20, 2018</h2>

      
    </header>

    


<p>Farà poc vaig posar un examen de recuperació en una assignatura que tractava d’una introducció a la teoria de jocs i estadística.</p>
<p>L’examen era tot tipus test, amb 4 possibles respostes i 40 preguntes, on les preguntes incorrectes resten.</p>
<p>A continuació podeu veure l’histograma de les notes, juntament amb l’histograma del nombre de preguntes correctes, incorrectes i en blanc.</p>
<pre><code>===========================================
Statistic   N   Mean  St. Dev.  Min   Max  
-------------------------------------------
Correctes   98 17.041  3.877     9     29  
Incorrectes 98 15.592  4.198     7     28  
Blanc       98 7.367   4.160     0     20  
Nota        98 34.806  10.841  8.500 68.500
-------------------------------------------</code></pre>
<center>
<img src="../../images/posts/recu1.png"/>
</center>
<center>
<img src="../../images/posts/recu2.png"/>
</center>
<p>Una de les preguntes involucrava calcular el valor esperat de una variable aleatòria. Curiosament, aquesta variable aleatòria era contestar una pregunta del test aleatòriament. El test estava disenyat tal que era un regal, el valor esperat de contestar una pregunta a l’atzar era molt elevada.</p>
<p>Aquí estic interessat en explorar la relació entre haver contestat correctament aquesta pregunta i la nota del test, ja que si un estudiant no es molt advers al risc (i sospito que els estudiants que van a l’examen de recuperació no ho son gaire) haurien de contestar totes les preguntes (deixar molt poques, o menys, preguntes en blanc), es una ganga.</p>
<p>El primer que he de fer es recalcular la nota del test sense tenir en compte la pregunta que vull analitzar, sinó es obvi que aquells que l’hagin encertat tindrán millor nota o un major (menor) nombre de preguntes correctes (incorrectes/en blanc). En el següent gràfic podem observar l’histograma de les notes ajustades per als que han respost la pregunta correctament i per als que l’han respost incorrectament o en blanc. També faig el mateix per al nombre de preguntes respostes en blanc.</p>
<p>El VERMELL representa alquells que sí han encertat la pregunta sobre el valor esperat de respondre aleatoriament una pregunta del test mentre que el BLAU representa aquells que no o que l’han deixat en blanc.</p>
<center>
<img src="../../images/posts/recu3.png"/>
</center>
<p>A primera vista, sembla que el grup VERMELL no sembla tenir una nota ajustada gaire superior (potser una mica) comparat a l’altre (BLAU) grup, es solapen molt els histogrames. El grup vermell té una nota mitja de 37.13813 i el grup blau de 34.01454.</p>
<p>També observem que el grup VERMELL deixa moltes menys preguntes en blanc comparat amb el grup BLAU, cosa que encaixa amb la nostra hipòtesis. El grup vermell ha deixat 4.967742 preguntes en blanc de mitja i el grup blau 7.80597.</p>
<p>El que podem fer ara es comparar les mitjes de les variables d’aquests dos grups amb algún test estadístic:</p>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Nota VERMELL and Nota BLAU
## t = 1.3416, df = 59.555, p-value = 0.1848
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -1.534366  7.781542
## sample estimates:
## mean of x mean of y 
##  37.13813  34.01454</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  Blanc VERMELL and Blanc BLAU
## t = -3.61, df = 66.072, p-value = 0.0005903
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -4.407903 -1.268553
## sample estimates:
## mean of x mean of y 
##  4.967742  7.805970</code></pre>
<pre><code>## 
##  Wilcoxon rank sum test with continuity correction
## 
## data:  Blanc VERMELL and Blanc BLAU
## W = 619, p-value = 0.001315
## alternative hypothesis: true location shift is not equal to 0
## 95 percent confidence interval:
##  -4.000020 -1.000034
## sample estimates:
## difference in location 
##              -2.999951</code></pre>
<p>Una vegada vists els resultats dels tests, podem afirmar que amb les dades que disposem (que segurament siguin masssa poques per a detectat efectes que no siguin molt grans, el poder del test es baix) no podem detectar una diferència estadísticament significativa entre les notes del grup VERMELL i del grup BLAU.</p>
<p>D’alte banda, podem afirmar que, amb les dades de les que disposem, ek gryo VERMELL han deixat menys preguntes (veure que el p-valor es de 0.0005903 en el test parámetric i de 0.001315 en el test no paramétric [que de fet es al que hauríem de prestar atenció, no pot ser que si esperem que la distribució estigui escorada cap al 0, i no pot pendre valors més petits que zero, segueixi una distribució normal]; així que encara que apliquéssim la correcció de Bontferroni degut a fer múltiples tests d’hipótesis, estaríem per sota de <span class="math inline">\(\alpha\)</span>/m=0,05/2=0,025 ) en blanc que el grup BLAU.</p>
<p>Sembla que aquells estudiants que saben calcular o apreciar correctament el valor esperat de contestar una pregunta aleatóriament, i assumint que són risc neutrals o poc aversos al risc, adopten una millor estratègia (si es que saben contestar preguntes aleatòriament, ja els humans som bastant dolents generant sèries aleatòries) que aquells que no ho saben apreciar. Tot i així, amb les dades que disposem no podem saber si això va repercutir positivament en la seva nota ajustada.</p>

  </article>

  <br/>

  
  
</section>

      </div>
      
        <footer class="footer">
  <section class="container">
    
     

  </section>
</footer>

      
    </main>

    

  <script src="../../js/app.js"></script>
  
  <script>
  (function($) {
    $(function() {
      $('#privateTrigger').on('click', function() {
        $('.private').slideToggle();
        $('#privateTriggerText').text(" ");
      });
    });
   })(jQuery);
  </script>
  
  </body>
</html>
